class LanguageManager:

    current_lang = "en"

    TEXTS = {
        "en": {

            "app_title": "🚀 LuciNet",
            "btn_dark": "🌙 Dark Mode",
            "btn_light": "☀️ Light Mode",
            "tab_dashboard": "📊 Dashboard",
            "tab_input": "📥 Input",
            "tab_archive": "🗄️ Archive",
            "tab_scanner": "📡 Scanner",
            "tab_rename": "✏️ Rename",
            "tab_export": "📤 Export",
            "tab_about": "ℹ️ About",

            "dash_title": "📊 System Dashboard",
            "dash_btn_refresh": " 🔄 Refresh Stats",
            "dash_btn_refreshing": "⏳ Calculating...",
            "dash_card_total": "Total Configs",
            "dash_card_valid": "Valid",
            "dash_card_timeout": "Timeout",
            "dash_card_error": "Error / Invalid",
            "dash_group_protocols": "Protocol Distribution",
            "dash_group_network": "Network Status (Averages)",
            "dash_avg_ping_prefix": "Average Ping:",
            "dash_untested_prefix": "Untested:",
            "dash_group_top_proxies": "🏆 Top Proxies (Lowest Ping)",
            "dash_menu_copy_single": "📋 Copy this config link",
            "dash_menu_copy_all": "📑 Copy all {count} top configs",
            "dash_msg_copy_single_title": "Copy Successful",
            "dash_msg_copy_single_body": "Config link copied successfully.",
            "dash_msg_copy_all_title": "Copy Multiple",
            "dash_msg_copy_all_body": "{count} configs copied successfully.",

            "input_lbl_group": "Save to Archive (Group):",
            "input_lbl_sub": "Subscription Link (Sub):",
            "input_placeholder_sub": "https://... (Separate multiple links with space or comma)",
            "input_btn_fetch": "⬇️ Download Configs",
            "input_btn_fetching": "⏳ Downloading...",
            "input_lbl_text_header": "Enter your configs here (or use the buttons):",
            "input_btn_load_file": "📂 Load from .txt file",
            "input_status_waiting": "Waiting for input...",
            "input_btn_import": "  Import Configs",
            "input_file_dialog_title": "Select Config File",
            "input_msg_file_success": "File successfully loaded into the text box.",
            "input_msg_error_title": "Error",
            "input_msg_error_file_read": "Error reading file:\n{e}",
            "input_msg_warn_no_sub": "Please enter at least one subscription link.",
            "input_msg_warn_invalid_sub": "No valid link found. (Links must start with http or https)",
            "input_status_downloading": "Downloading configs from network...",
            "input_status_fetch_success": "Configs successfully downloaded and ready for import.",
            "input_msg_fetch_success_title": "Download Successful",
            "input_msg_fetch_success_body": "Subscription links content successfully extracted and added to the text box.\nYou can review them and then press Import.",
            "input_msg_fetch_warn_body": "\n\n⚠️ Warning: Some links failed:\n{errors}",
            "input_status_fetch_no_config": "Link downloaded but no config found.",
            "input_msg_fetch_no_config_body": "No config extracted from the links.",
            "input_status_fetch_error": "Error downloading sub link",
            "input_msg_fetch_error_title": "Connection Error",
            "input_msg_fetch_error_body": "A problem occurred while downloading the subscription link:\n{err_msg}",
            "input_msg_warn_no_links": "Please enter the links first.",
            "input_msg_warn_no_valid_configs": "No valid configs found.\nErrors count: {errors}",
            "input_status_saving": "Saving {count} configs...",
            "input_msg_import_success_body": "Operation successful! {total} configs saved.",
            "input_msg_import_success_errors": "\n({errors} invalid links ignored)",
            "input_status_ready": "Ready",
            "input_msg_import_report_title": "Import Report",
            "input_status_import_error": "Storage Error",
            "input_msg_import_error_body": "A problem occurred:\n{err_msg}",

            "arc_lbl_archive": "Show Archive:",
            "arc_cmb_all_archives": "All Archives",
            "arc_btn_new_archive": "➕ Create Archive",
            "arc_btn_rename": "  Rename",
            "arc_btn_delete": "  Delete Archive",
            "arc_btn_tools": "🛠 Tools",
            "arc_menu_move": "📦 Move selected to another archive...",
            "arc_menu_dedup": "🧹 Remove duplicate configs (Smart)",
            "arc_menu_del_sel": "✂️ Delete selected configs",
            "arc_menu_del_inv": "🗑 Delete invalid configs (Invalid/Error)",
            "arc_menu_del_tout": "⏳ Delete timeouts",
            "arc_group_filter": "Advanced Search & Filter",
            "arc_placeholder_search": "Search in Remark or Server address...",
            "arc_lbl_search": "🔍 Search:",
            "arc_lbl_status": "Status:",
            "arc_lbl_protocol": "Protocol:",
            "arc_cmb_all_statuses": "All Statuses",
            "arc_cmb_all_protocols": "All Protocols",
            "arc_lbl_count": "Count: {count}",
            "arc_status_ready": "Ready",
            "arc_btn_refresh": " 🔄 Refresh Data",
            "arc_btn_loading": "  Loading...",
            "arc_msg_new_title": "New Archive",
            "arc_msg_new_prompt": "Enter the new archive name:",
            "arc_msg_created_title": "Archive Created",
            "arc_msg_created_body": "Archive '{name}' created.\nYou can now move configs to this archive using the 'Tools' button.",
            "arc_msg_rename_title": "Rename Archive",
            "arc_msg_rename_prompt": "New name for archive '{name}':",
            "arc_msg_delete_title": "Confirm Deletion",
            "arc_msg_delete_body": "Warning: Are you sure you want to completely delete archive '{name}'?\nAll configs inside will be permanently lost!",
            "arc_msg_error_title": "Error",
            "arc_msg_no_selection": "No config selected.",
            "arc_msg_move_title": "Move Configs",
            "arc_msg_move_prompt": "Specify destination for {count} selected configs:",
            "arc_msg_move_success": "{count} configs successfully moved.",
            "arc_msg_del_sel_body": "Are you sure you want to delete {count} selected configs?",
            "arc_msg_clean_title": "Cleanup",
            "arc_msg_no_invalid": "No invalid configs found in this list.",
            "arc_msg_del_inv_body": "Are you sure you want to delete {count} invalid configs?",
            "arc_msg_no_timeout": "No timeout configs found in this list.",
            "arc_msg_del_tout_body": "Are you sure you want to delete {count} timeout configs?",
            "arc_msg_dedup_title": "Scan Result",
            "arc_msg_no_dedup": "No duplicate configs found!\nYour archive is perfectly clean.",
            "arc_msg_del_dedup_title": "Remove Duplicates",
            "arc_msg_del_dedup_body": "Found {count} duplicate configs in this archive!\nDo you want to delete the extra copies?",
            "arc_msg_del_success": "{count} configs successfully deleted.",
            "arc_msg_op_success": "Operation Successful",
            "arc_status_db_error": "Database connection error",
            "arc_ctx_copy": "📋 Copy Link",
            "arc_ctx_qr": "📱 Show QR Code",
            "arc_ctx_speed": "⚡ Download Speed Test ({count} items)",
            "arc_ctx_move": "🔄 Move {count} items to group...",
            "arc_ctx_delete": "❌ Delete {count} configs",
            "arc_msg_copied_title": "Copied",
            "arc_msg_copied_body": "Config link copied.",
            "arc_status_speed_init": "Speed Test (0 of {total})...",
            "arc_status_speed_prog": "Speed Test ({current} of {total})...",
            "arc_status_speed_done": "Speed Test Finished.",
            "arc_msg_speed_done_title": "Finished",
            "arc_msg_speed_done_body": "Batch speed test completed.",

            "scn_lbl_archive": "Select Archive:",
            "scn_cmb_all_archives": "All Archives",
            "scn_btn_refresh": " 🔄 Refresh",
            "scn_btn_load_untested": "  Load Untested",
            "scn_btn_load_all": "  Load All",
            "scn_lbl_concurrent": "Concurrent:",
            "scn_lbl_timeout": "Timeout(s):",
            "scn_lbl_speed_size": "Speed Test Size:",
            "scn_speed_200": "200 KB (Quick)",
            "scn_speed_500": "500 KB (Balanced)",
            "scn_speed_2000": "2 MB (Extended)",
            "scn_btn_scan_sel": "  Scan Selected",
            "scn_btn_scan_all": "  Scan All Loaded",
            "scn_btn_stop": "  Stop",
            "scn_status_ready": "Ready",
            "scn_group_filter": "Real-time Table Filters",
            "scn_placeholder_search": "Search in Name or Server...",
            "scn_lbl_search": "🔍 Search:",
            "scn_lbl_status": "Status:",
            "scn_cmb_all_statuses": "All Statuses",
            "scn_lbl_protocol": "Protocol:",
            "scn_cmb_all_protocols": "All Protocols",
            "scn_status_loading": "Loading...",
            "scn_status_loaded": "{count} configs loaded.",
            "scn_status_scan_start": "Starting scan...",
            "scn_status_scanning": "Scanning... {current} of {total} (Ping: {ping}ms)",
            "scn_status_scan_done": "Scan finished!",
            "scn_status_scan_error": "Scan error!",
            "scn_status_stopping": "Safely stopping cores (please wait)...",
            "scn_ctx_copy": "📋 Copy Link",
            "scn_ctx_qr": "📱 Show QR Code",
            "scn_ctx_speed": "⚡ Download Speed Test ({count} items)",
            "scn_ctx_move": "🔄 Move {count} items to group...",
            "scn_ctx_delete": "❌ Delete {count} configs",
            "scn_msg_copied_title": "Copied",
            "scn_msg_copied_body": "Config link copied.",
            "scn_status_speed_init": "Speed Test (0 of {total})...",
            "scn_status_speed_prog": "Speed Test ({current} of {total})...",
            "scn_status_speed_done": "Speed Test Finished.",
            "scn_msg_speed_done_title": "Finished",
            "scn_msg_speed_done_body": "Batch speed test completed.",
            "scn_msg_move_title": "Move",
            "scn_msg_move_multi_prompt": "Select destination group for {count} configs:",
            "scn_msg_move_single_prompt": "Select destination group for '{remark}':",
            "scn_msg_del_title": "Confirm Deletion",
            "scn_msg_del_multi_prompt": "Are you sure you want to delete {count} configs?",
            "scn_msg_del_single_prompt": "Are you sure you want to permanently delete '{remark}'?",
            "scn_msg_speed_test_title": "Speed Test",
            "scn_msg_speed_test_body": "Speed test started in the background...\nThis might take a few seconds.",
            "scn_msg_speed_res_title": "Result",
            "scn_msg_speed_res_body": "Speed test successfully completed:\n{speed} MB/s",
            "scn_msg_error_title": "Error",
            "scn_msg_speed_fail_body": "Speed test failed (possibly due to internet disconnection or blocked server).",

            "ren_group_target": "Target Audience",
            "ren_cmb_all_archives": "All Archives",
            "ren_cmb_valid_only": "Valid Only",
            "ren_cmb_all_configs": "All Configs",
            "ren_tooltip_refresh": "Refresh Archives List",
            "ren_lbl_archive": "Select Archive:",
            "ren_lbl_status": "Status:",
            "ren_group_settings": "Rename Settings",
            "ren_chk_clear_old": "Clear Old Name (Overwrite)",
            "ren_lbl_clear": "Cleanup:",
            "ren_placeholder_prefix": "Add to start of the name...",
            "ren_lbl_prefix": "Prefix:",
            "ren_placeholder_suffix": "Add to end of the name...",
            "ren_lbl_suffix": "Suffix:",
            "ren_cmb_emoji_none": "No Emoji",
            "ren_cmb_emoji_food": "Food (Random)",
            "ren_cmb_emoji_animal": "Animals (Random)",
            "ren_cmb_emoji_fire": "🔥 Fire",
            "ren_cmb_emoji_check": "✅ Check",
            "ren_cmb_emoji_rocket": "🚀 Rocket",
            "ren_cmb_emoji_lightning": "⚡ Lightning",
            "ren_cmb_emoji_crown": "👑 Crown",
            "ren_cmb_emoji_star": "⭐ Star",
            "ren_cmb_emoji_diamond": "💎 Diamond",
            "ren_cmb_emoji_start": "Start of Name",
            "ren_cmb_emoji_end": "End of Name",
            "ren_lbl_emoji": "Emoji:",
            "ren_chk_number": "Auto Numbering (01, 02, ...)",
            "ren_lbl_index": "Index:",
            "ren_btn_apply": "🚀 Apply Changes to Database",
            "ren_btn_processing": "⏳ Processing...",
            "ren_msg_no_change_title": "No Change",
            "ren_msg_no_change_body": "No config found with these criteria!",
            "ren_msg_success_title": "Operation Successful",
            "ren_msg_success_body": "{count} configs renamed and saved to the database!\nPlease refresh the Archive or Scanner tab (Load All).",
            "ren_msg_error_title": "System Error",
            "ren_msg_error_body": "An error occurred during renaming:\n{err_msg}",

            "exp_group_settings": "Config Export Settings",
            "exp_lbl_archive": "Select Archive:",
            "exp_cmb_all_archives": "All Archives (Full Database)",
            "exp_btn_refresh": "🔄 Refresh List",
            "exp_lbl_info": "You can export all configs or only valid configs from the selected archive.",
            "exp_btn_export_all": "  Export All Configs",
            "exp_btn_export_valid": "  Export Valid Configs",
            "exp_cmb_archive_prefix": "Archive: {name}",
            "exp_msg_no_config_title": "Error",
            "exp_msg_no_config_body": "No config found matching these criteria for export.",
            "exp_dialog_title": "Save Config File",
            "exp_msg_success_title": "Success",
            "exp_msg_success_body": "{count} configs successfully exported to:\n{path}",
            "exp_msg_error_title": "Save Error",
            "exp_msg_error_body": "A problem occurred:\n{err_msg}",
            "exp_msg_db_error_title": "Database Error",
            "exp_msg_db_error_body": "Error retrieving data:\n{err_msg}",

            "abt_desc": "LuciNet is a modern, fast, and multi-threaded proxy configuration management and scanning tool.\nBuilt with Python and Xray-core, it delivers high-speed and precise scanning for massive configuration databases.",
            "abt_btn_github": "⭐ Star us on GitHub",
        },
        "fa": {

            "app_title": "🚀 لوسی نت",
            "btn_dark": "🌙 حالت تاریک",
            "btn_light": "☀️ حالت روشن",
            "tab_dashboard": "📊 داشبورد",
            "tab_input": "📥 ورودی",
            "tab_archive": "🗄️ آرشیو",
            "tab_scanner": "📡 اسکنر",
            "tab_rename": "✏️ تغییر نام",
            "tab_export": "📤 خروجی",
            "tab_about": "ℹ️ درباره برنامه",

            "dash_title": "📊 داشبورد وضعیت سیستم",
            "dash_btn_refresh": " 🔄 به‌روزرسانی آمار",
            "dash_btn_refreshing": "⏳ در حال محاسبه...",
            "dash_card_total": "کل کانفیگ‌ها",
            "dash_card_valid": "سالم (Valid)",
            "dash_card_timeout": "تایم‌اوت",
            "dash_card_error": "خطا / نامعتبر",
            "dash_group_protocols": "توزیع پروتکل‌ها",
            "dash_group_network": "وضعیت شبکه (میانگین‌ها)",
            "dash_avg_ping_prefix": "میانگین پینگ:",
            "dash_untested_prefix": "اسکن نشده:",
            "dash_group_top_proxies": "🏆 برترین کانفیگ‌ها (کمترین پینگ)",
            "dash_menu_copy_single": "📋 کپی لینک همین کانفیگ",
            "dash_menu_copy_all": "📑 کپی همه {count} کانفیگ برتر",
            "dash_msg_copy_single_title": "کپی تکی",
            "dash_msg_copy_single_body": "لینک کانفیگ با موفقیت کپی شد.",
            "dash_msg_copy_all_title": "کپی گروهی",
            "dash_msg_copy_all_body": "{count} کانفیگ با موفقیت کپی شد.",

            "input_lbl_group": "ذخیره در آرشیو (گروه):",
            "input_lbl_sub": "لینک اشتراک (Sub):",
            "input_placeholder_sub": "https://... (برای چند لینک با فاصله یا کاما جدا کنید)",
            "input_btn_fetch": "⬇️ دانلود کانفیگ‌ها",
            "input_btn_fetching": "⏳ در حال دریافت...",
            "input_lbl_text_header": "کانفیگ‌های خود را اینجا وارد کنید (یا از دکمه‌ها استفاده کنید):",
            "input_btn_load_file": "📂 بارگذاری از فایل txt.",
            "input_status_waiting": "منتظر ورود اطلاعات...",
            "input_btn_import": "  Import Configs",
            "input_file_dialog_title": "انتخاب فایل کانفیگ",
            "input_msg_file_success": "فایل با موفقیت در کادر بارگذاری شد.",
            "input_msg_error_title": "خطا",
            "input_msg_error_file_read": "خطا در خواندن فایل:\n{e}",
            "input_msg_warn_no_sub": "لطفاً حداقل یک لینک اشتراک وارد کنید.",
            "input_msg_warn_invalid_sub": "لینک معتبری یافت نشد. (لینک‌ها باید با http یا https شروع شوند)",
            "input_status_downloading": "در حال دانلود کانفیگ‌ها از شبکه...",
            "input_status_fetch_success": "کانفیگ‌ها با موفقیت دریافت و آماده ایمپورت هستند.",
            "input_msg_fetch_success_title": "دریافت موفق",
            "input_msg_fetch_success_body": "محتوای لینک‌های اشتراک با موفقیت استخراج و به کادر متنی اضافه شد.\nمی‌توانید بررسی کنید و سپس دکمه Import را بزنید.",
            "input_msg_fetch_warn_body": "\n\n⚠️ هشدار: برخی لینک‌ها با خطا مواجه شدند:\n{errors}",
            "input_status_fetch_no_config": "لینک دریافت شد اما کانفیگی یافت نشد.",
            "input_msg_fetch_no_config_body": "هیچ کانفیگی از لینک‌ها استخراج نشد.",
            "input_status_fetch_error": "خطا در دانلود ساب‌لینک",
            "input_msg_fetch_error_title": "خطا در ارتباط",
            "input_msg_fetch_error_body": "مشکلی در دانلود لینک اشتراک پیش آمد:\n{err_msg}",
            "input_msg_warn_no_links": "لطفاً ابتدا لینک‌ها را وارد کنید.",
            "input_msg_warn_no_valid_configs": "هیچ کانفیگ معتبری یافت نشد.\nتعداد خطاها: {errors}",
            "input_status_saving": "در حال ذخیره {count} کانفیگ...",
            "input_msg_import_success_body": "عملیات موفق! {total} کانفیگ ذخیره شد.",
            "input_msg_import_success_errors": "\n(تعداد {errors} لینک نامعتبر نادیده گرفته شد)",
            "input_status_ready": "آماده",
            "input_msg_import_report_title": "گزارش Import",
            "input_status_import_error": "خطا در ذخیره‌سازی",
            "input_msg_import_error_body": "مشکلی رخ داد:\n{err_msg}",

            "arc_lbl_archive": "نمایش آرشیو:",
            "arc_cmb_all_archives": "همه آرشیوها",
            "arc_btn_new_archive": "➕ ساخت آرشیو",
            "arc_btn_rename": "  تغییر نام",
            "arc_btn_delete": "  حذف آرشیو",
            "arc_btn_tools": "🛠 ابزارها",
            "arc_menu_move": "📦 انتقال انتخاب‌شده‌ها به آرشیو دیگر...",
            "arc_menu_dedup": "🧹 حذف کانفیگ‌های تکراری (هوشمند)",
            "arc_menu_del_sel": "✂️ حذف کانفیگ‌های انتخاب‌شده",
            "arc_menu_del_inv": "🗑 حذف نامعتبرها (Invalid/Error)",
            "arc_menu_del_tout": "⏳ حذف تایم‌اوت‌ها (Timeout)",
            "arc_group_filter": "جستجو و فیلتر پیشرفته",
            "arc_placeholder_search": "جستجو در نام (Remark) یا آدرس سرور...",
            "arc_lbl_search": "🔍 جستجو:",
            "arc_lbl_status": "وضعیت:",
            "arc_lbl_protocol": "پروتکل:",
            "arc_cmb_all_statuses": "همه وضعیت‌ها",
            "arc_cmb_all_protocols": "همه پروتکل‌ها",
            "arc_lbl_count": "تعداد: {count}",
            "arc_status_ready": "آماده",
            "arc_btn_refresh": " 🔄 Refresh Data",
            "arc_btn_loading": "  Loading...",
            "arc_msg_new_title": "آرشیو جدید",
            "arc_msg_new_prompt": "نام آرشیو جدید را وارد کنید:",
            "arc_msg_created_title": "آرشیو ایجاد شد",
            "arc_msg_created_body": "آرشیو '{name}' ساخته شد.\nاکنون می‌توانید از طریق دکمه «🛠 ابزارها» کانفیگ‌های خود را به این آرشیو منتقل کنید.",
            "arc_msg_rename_title": "تغییر نام آرشیو",
            "arc_msg_rename_prompt": "نام جدید برای آرشیو '{name}':",
            "arc_msg_delete_title": "تایید حذف",
            "arc_msg_delete_body": "هشدار: آیا از حذف کامل آرشیو '{name}' مطمئن هستید؟\nتمام کانفیگ‌های داخل این آرشیو برای همیشه پاک خواهند شد!",
            "arc_msg_error_title": "خطا",
            "arc_msg_no_selection": "هیچ کانفیگی انتخاب نشده است.",
            "arc_msg_move_title": "انتقال کانفیگ",
            "arc_msg_move_prompt": "مقصد {count} کانفیگ انتخاب‌شده را مشخص کنید:",
            "arc_msg_move_success": "{count} کانفیگ با موفقیت منتقل شد.",
            "arc_msg_del_sel_body": "آیا از حذف {count} کانفیگ انتخاب‌شده مطمئن هستید؟",
            "arc_msg_clean_title": "پاکسازی",
            "arc_msg_no_invalid": "هیچ کانفیگ نامعتبری در این لیست یافت نشد.",
            "arc_msg_del_inv_body": "آیا از حذف {count} کانفیگ نامعتبر مطمئن هستید؟",
            "arc_msg_no_timeout": "هیچ کانفیگ تایم‌اوت شده‌ای در این لیست یافت نشد.",
            "arc_msg_del_tout_body": "آیا از حذف {count} کانفیگ تایم‌اوت مطمئن هستید؟",
            "arc_msg_dedup_title": "نتیجه بررسی",
            "arc_msg_no_dedup": "هیچ کانفیگ تکراری در این آرشیو یافت نشد!\nآرشیو فعلی شما کاملاً تمیز است.",
            "arc_msg_del_dedup_title": "حذف تکراری‌ها",
            "arc_msg_del_dedup_body": "تعداد {count} کانفیگ تکراری در این آرشیو پیدا شد!\nآیا مایلید نسخه‌های اضافه را حذف کنید؟",
            "arc_msg_del_success": "تعداد {count} کانفیگ با موفقیت حذف شد.",
            "arc_msg_op_success": "عملیات موفق",
            "arc_status_db_error": "خطا در ارتباط با دیتابیس",
            "arc_ctx_copy": "📋 کپی لینک",
            "arc_ctx_qr": "📱 نمایش QR Code",
            "arc_ctx_speed": "⚡ تست سرعت دانلود ({count} مورد)",
            "arc_ctx_move": "🔄 انتقال {count} مورد به گروه...",
            "arc_ctx_delete": "❌ حذف {count} کانفیگ",
            "arc_msg_copied_title": "کپی شد",
            "arc_msg_copied_body": "لینک کانفیگ کپی شد.",
            "arc_status_speed_init": "تست سرعت (0 از {total})...",
            "arc_status_speed_prog": "تست سرعت ({current} از {total})...",
            "arc_status_speed_done": "تست سرعت پایان یافت.",
            "arc_msg_speed_done_title": "پایان",
            "arc_msg_speed_done_body": "تست سرعت به پایان رسید.",

            "scn_lbl_archive": "انتخاب آرشیو:",
            "scn_cmb_all_archives": "همه آرشیوها",
            "scn_btn_refresh": " 🔄 Refresh",
            "scn_btn_load_untested": "  Load Untested",
            "scn_btn_load_all": "  Load All",
            "scn_lbl_concurrent": "همزمان:",
            "scn_lbl_timeout": "تایم‌اوت(s):",
            "scn_lbl_speed_size": "حجم تست سرعت:",
            "scn_speed_200": "200 KB (سریع)",
            "scn_speed_500": "500 KB (متعادل)",
            "scn_speed_2000": "2 MB (گسترده)",
            "scn_btn_scan_sel": "  Scan Selected",
            "scn_btn_scan_all": "  Scan All Loaded",
            "scn_btn_stop": "  Stop",
            "scn_status_ready": "آماده",
            "scn_group_filter": "فیلترهای لحظه‌ای جدول",
            "scn_placeholder_search": "جستجو در نام یا سرور...",
            "scn_lbl_search": "🔍 جستجو:",
            "scn_lbl_status": "وضعیت:",
            "scn_cmb_all_statuses": "همه وضعیت‌ها",
            "scn_lbl_protocol": "پروتکل:",
            "scn_cmb_all_protocols": "همه پروتکل‌ها",
            "scn_status_loading": "در حال بارگذاری...",
            "scn_status_loaded": "{count} کانفیگ بارگذاری شد.",
            "scn_status_scan_start": "شروع اسکن...",
            "scn_status_scanning": "درحال اسکن... {current} از {total} (پینگ: {ping}ms)",
            "scn_status_scan_done": "اسکن تمام شد!",
            "scn_status_scan_error": "خطا در اسکن!",
            "scn_status_stopping": "در حال توقف امن هسته‌ها (چند ثانیه صبر کنید)...",
            "scn_ctx_copy": "📋 کپی لینک",
            "scn_ctx_qr": "📱 نمایش QR Code",
            "scn_ctx_speed": "⚡ تست سرعت دانلود ({count} مورد)",
            "scn_ctx_move": "🔄 انتقال {count} مورد به گروه...",
            "scn_ctx_delete": "❌ حذف {count} کانفیگ",
            "scn_msg_copied_title": "کپی شد",
            "scn_msg_copied_body": "لینک کانفیگ کپی شد.",
            "scn_status_speed_init": "تست سرعت (0 از {total})...",
            "scn_status_speed_prog": "تست سرعت ({current} از {total})...",
            "scn_status_speed_done": "تست سرعت پایان یافت.",
            "scn_msg_speed_done_title": "پایان",
            "scn_msg_speed_done_body": "تست سرعت دسته‌جمعی به پایان رسید.",
            "scn_msg_move_title": "انتقال",
            "scn_msg_move_multi_prompt": "گروه مقصد برای {count} کانفیگ را انتخاب کنید:",
            "scn_msg_move_single_prompt": "گروه مقصد برای '{remark}' را انتخاب کنید:",
            "scn_msg_del_title": "تایید حذف",
            "scn_msg_del_multi_prompt": "آیا از حذف {count} کانفیگ مطمئن هستید؟",
            "scn_msg_del_single_prompt": "آیا از حذف دائم '{remark}' مطمئن هستید؟",
            "scn_msg_speed_test_title": "تست سرعت",
            "scn_msg_speed_test_body": "تست سرعت در پس‌زمینه شروع شد...\nاین کار ممکن است چند ثانیه طول بکشد.",
            "scn_msg_speed_res_title": "نتیجه",
            "scn_msg_speed_res_body": "تست سرعت با موفقیت انجام شد:\n{speed} MB/s",
            "scn_msg_error_title": "خطا",
            "scn_msg_speed_fail_body": "تست سرعت ناموفق بود (احتمالاً قطعی اینترنت یا مسدود بودن سرور).",

            "ren_group_target": "جامعه هدف (Target)",
            "ren_cmb_all_archives": "همه آرشیوها",
            "ren_cmb_valid_only": "فقط سالم (Valid)",
            "ren_cmb_all_configs": "همه کانفیگ‌ها",
            "ren_tooltip_refresh": "بروزرسانی لیست آرشیوها",
            "ren_lbl_archive": "انتخاب آرشیو:",
            "ren_lbl_status": "وضعیت:",
            "ren_group_settings": "تنظیمات تغییر نام",
            "ren_chk_clear_old": "حذف نام قبلی (Overwrite)",
            "ren_lbl_clear": "پاکسازی:",
            "ren_placeholder_prefix": "اضافه شدن به ابتدای نام...",
            "ren_lbl_prefix": "پیشوند (Prefix):",
            "ren_placeholder_suffix": "اضافه شدن به انتهای نام...",
            "ren_lbl_suffix": "پسوند (Suffix):",
            "ren_cmb_emoji_none": "بدون ایموجی",
            "ren_cmb_emoji_food": "غذا (تصادفی)",
            "ren_cmb_emoji_animal": "حیوانات (تصادفی)",
            "ren_cmb_emoji_fire": "آتش 🔥",
            "ren_cmb_emoji_check": "تیک ✅",
            "ren_cmb_emoji_rocket": "موشک 🚀",
            "ren_cmb_emoji_lightning": "رعد و برق ⚡",
            "ren_cmb_emoji_crown": "تاج 👑",
            "ren_cmb_emoji_star": "ستاره ⭐",
            "ren_cmb_emoji_diamond": "الماس 💎",
            "ren_cmb_emoji_start": "ابتدای نام",
            "ren_cmb_emoji_end": "انتهای نام",
            "ren_lbl_emoji": "ایموجی:",
            "ren_chk_number": "شماره‌گذاری خودکار (01, 02, ...)",
            "ren_lbl_index": "ایندکس:",
            "ren_btn_apply": "🚀 اعمال تغییرات روی دیتابیس",
            "ren_btn_processing": "⏳ در حال پردازش...",
            "ren_msg_no_change_title": "بدون تغییر",
            "ren_msg_no_change_body": "هیچ کانفیگی با این مشخصات یافت نشد!",
            "ren_msg_success_title": "عملیات موفق",
            "ren_msg_success_body": "نام {count} کانفیگ تغییر یافت و در دیتابیس ذخیره شد!\nلطفاً تب Archive یا Scanner را رفرش کنید (Load All).",
            "ren_msg_error_title": "خطای سیستمی",
            "ren_msg_error_body": "مشکلی در تغییر نام رخ داد:\n{err_msg}",

            "exp_group_settings": "تنظیمات خروجی کانفیگ‌ها",
            "exp_lbl_archive": "انتخاب آرشیو:",
            "exp_cmb_all_archives": "همه آرشیوها (کل دیتابیس)",
            "exp_btn_refresh": "🔄 بروزرسانی لیست",
            "exp_lbl_info": "شما می‌توانید از آرشیو انتخاب‌شده، تمام کانفیگ‌ها یا فقط کانفیگ‌های سالم را خروجی بگیرید.",
            "exp_btn_export_all": "  خروجی از همه کانفیگ‌ها",
            "exp_btn_export_valid": "  خروجی از کانفیگ‌های سالم (Valid)",
            "exp_cmb_archive_prefix": "آرشیو: {name}",
            "exp_msg_no_config_title": "خطا",
            "exp_msg_no_config_body": "هیچ کانفیگی با این مشخصات برای خروجی گرفتن یافت نشد.",
            "exp_dialog_title": "ذخیره فایل کانفیگ‌ها",
            "exp_msg_success_title": "موفقیت",
            "exp_msg_success_body": "تعداد {count} کانفیگ با موفقیت صادر شد:\n{path}",
            "exp_msg_error_title": "خطا در ذخیره",
            "exp_msg_error_body": "مشکلی پیش آمد:\n{err_msg}",
            "exp_msg_db_error_title": "خطای دیتابیس",
            "exp_msg_db_error_body": "خطا در دریافت اطلاعات:\n{err_msg}",

            "abt_desc": "نرم‌افزار LuciNet یک ابزار قدرتمند، سریع و چند‌رشته‌ای برای مدیریت، بررسی و اسکن کانفیگ‌های پروکسی است.\nاین ابزار با بهره‌گیری از هسته قدرتمند Xray-core و زبان Python ساخته شده و اسکن سریع و دقیقی را برای دیتابیس‌های عظیم کانفیگ ارائه می‌دهد.",
            "abt_btn_github": "⭐ ما را در گیت‌هاب دنبال کنید",
        },
    }

    @classmethod
    def tr(cls, key):

        return cls.TEXTS.get(cls.current_lang, {}).get(key, key)

    @classmethod
    def toggle_language(cls):

        cls.current_lang = "fa" if cls.current_lang == "en" else "en"
        return cls.current_lang
